version: '3'

services:

  mongo:
    image: mongo:3.6.13
    container_name: "mongo"
    #restart: always
    ports:
      - 27018:27017
    volumes:
      - mongodb:/data/db

  postgresql:
    image: postgres:10.9
    container_name: "postgresql"
    #restart: always
    ports:
      - 5433:5432
    volumes:
      - postgresql:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"

volumes:
  postgresql:
    external: false
  mongodb:
    external: false
